function [] = draw_skeleton_vector_graphics(C,BE)

line_width = 5;%2
marker_size = 20;%8

hold on;

if(size(C,2)==2)
    plot( ...
        [C(BE(:,1),1) C(BE(:,2),1)]', ...
        [C(BE(:,1),2) C(BE(:,2),2)]', ...
        '-w', ...
        'LineWidth',1.0*line_width);
    
    plot( ...
        [C(BE(:,1),1) C(BE(:,2),1)]', ...
        [C(BE(:,1),2) C(BE(:,2),2)]', ...
        '-k', ...
        'LineWidth',0.6*line_width);
    
    plot( ...
        [C(BE(:,1),1) C(BE(:,2),1)]', ...
        [C(BE(:,1),2) C(BE(:,2),2)]', ...
        'Color', [106./255.,106./255.,255./255.], ...
        'LineWidth',0.4*line_width);
%, ...
    %'MarkerSize',marker_size, ...
    %'MarkerEdgeColor','k', ...
    %'MarkerFaceColor','y');


    scatter(C(:,1),C(:,2),line_width*30*ones(size(C,1),1),'w','filled');
    scatter(C(:,1),C(:,2),line_width*18*ones(size(C,1),1),'k','filled');
    scatter(C(:,1),C(:,2),line_width*12*ones(size(C,1),1),[239./255.,213./255.,46./255.],'filled');
else
    plot3( ...
    [C(BE(:,1),1) C(BE(:,2),1)]', ...
    [C(BE(:,1),2) C(BE(:,2),2)]', ...
    [C(BE(:,1),3) C(BE(:,2),3)]', ...
    '-bo', ...
    'LineWidth',line_width, ...
    'MarkerSize',marker_size, ...
    'MarkerEdgeColor','k', ...
    'MarkerFaceColor','y');
end



axis equal;